# Generated by Django 3.2.4 on 2021-06-29 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaviType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='white', max_length=100)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 29, 8, 24, 28, 548275, tzinfo=utc))),
            ],
            options={
                'db_table': 'Lavi',
            },
        ),
    ]
